# Generated by Django 2.0.7 on 2018-07-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist_text',
            new_name='artist_name',
        ),
        migrations.AlterField(
            model_name='artist',
            name='est_date',
            field=models.IntegerField(verbose_name='date established'),
        ),
    ]
