# Generated by Django 2.0.7 on 2018-07-19 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20180719_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song',
            new_name='artist_id',
        ),
    ]
