# Generated by Django 2.0.7 on 2018-07-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20180719_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='birth_date',
            field=models.DateField(default=0.0005208333333333333, verbose_name='date born'),
            preserve_default=False,
        ),
    ]
