# Generated by Django 2.0.7 on 2018-07-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_artist_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birth_date',
            field=models.DateField(verbose_name='date_born'),
        ),
    ]
