# Generated by Django 2.0.7 on 2018-07-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_auto_20180719_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='birth_date',
        ),
    ]
